version: '4.4.4'
services:
#   rtmp:
#     build: ./rtmp
#     ports:
#       - '1935:1935'
#       - '8080:8080'
#     container_name: rtmp_server
#     volumes:
#       - ./data:/tmp/hls

  official_web:
    restart: on-failure
    build: ./
    # env_file: ./.env.production

    container_name: bitechly_web
    ports:
      - '8082:8082'
      # - '80:80'
    environment:
      - ./.env
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules/
      # - ./../uploads:/usr/uploads/

  # db:
  #   image: mongo
  #   container_name: westream
  #   volumes:
  #     - mongodata:/data/db
  #   ports:
  #     - '27017:27017'

# volumes:
#   mongodata:
